"""re_elicitacao_flow

Revision ID: 6ccf10e2a7db
Revises: bb83169459ce
Create Date: 2026-06-01 16:55:32.753341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ccf10e2a7db'
down_revision: Union[str, None] = 'bb83169459ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos_requisitos', sa.Column('categorias_concluidas', sa.JSON(), nullable=True))
    op.add_column('projetos_requisitos', sa.Column('re_elicitacao_motivo', sa.Text(), nullable=True))
    op.add_column('projetos_requisitos', sa.Column('re_elicitacao_origem', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projetos_requisitos', 're_elicitacao_origem')
    op.drop_column('projetos_requisitos', 're_elicitacao_motivo')
    op.drop_column('projetos_requisitos', 'categorias_concluidas')
    # ### end Alembic commands ###
